#!/usr/bin/env python3
"""Regenerate mrsim-lib.js from the MRSIM Steam install.

MRSIM (Multi Rotor SIM) packs all game data into a single archive,
MRSIM.dkb. The format is a plain file table followed by raw file blobs:

  header:  u64 table_offset, u64 ?, u32 ?, u32 file_count
  record:  u64 record_size, u64 flags, u64 file_size, u64 data_offset,
           u32 path_len, u32 tag ('r','l'), char[path_len] path
  data:    starts right after the last record; offsets are relative to it

Track objects (gates, poles, cubes, flags, mats...) are small XML files
referenced by tracks via <Include>/<Instance macro>. This script extracts
the ones the viewer needs and embeds them into mrsim-lib.js so the viewer
stays a static site. Re-run after a game update:

    python3 export_mrsim_lib.py [path-to-MRSIM.dkb]
"""
import struct
import sys
from pathlib import Path

DKB = Path.home() / ".local/share/Steam/steamapps/common/MRSIM/MRSIM.dkb"
OUT = Path(__file__).parent / "mrsim-lib.js"

BASE = "/Data/Simulations/Multirotor/"
# every object a track can place that the viewer knows how to draw
LIB_FILES = [
    "5x5Gate.xml", "5x5StartFinishGate.xml",
    "7x6Gate.xml", "7x6StartFinishGate.xml",
    "5x5Tower.xml", "7x6Tower.xml",
    "4x7Hurdle.xml", "5x10Hurdle.xml", "7x16Hurdle.xml",
    "DiveGate.xml", "7x7DiveGate.xml", "7x7ClimbGate.xml",
    "7x7DiveBox.xml", "7x7DiveBoxCorner.xml", "CarouselDown.xml",
    "7x7Mat.xml", "StartBlock.xml",
    "Flag.xml", "Flag180.xml", "FlagPassRight.xml", "FlagPassLeft.xml",
    "HalfPlanePassageRight.xml", "HalfPlanePassageLeft.xml",
    "DroneTrackInstanceGroups.xml",
    # the drone's own arm LED: a BinaryModelRenderer whose default material
    # (DroneRenderingMaterials.xml "LEDLighting") is PBREmissive — the one
    # light-emitting thing the game ships that a track can <Include> directly
    "RaceLEDs.xml",
    "Gates/PoleGates.xml", "Gates/Champs25Gate.xml", "Gates/Champs25Pole.xml",
    "LaunchStands/MetalLaunchStand.xml",
    "LaunchStands/ChampionshipLaunchStand.xml",
    "Furniture/ShadeCanopy.xml",
]


def read_dkb_table(path):
    data = path.read_bytes()
    table_off, = struct.unpack_from("<Q", data, 0)
    count, = struct.unpack_from("<I", data, 20)
    pos = table_off
    entries = {}
    for _ in range(count):
        rec_size, _flags, fsize, foff = struct.unpack_from("<QQQQ", data, pos)
        plen, = struct.unpack_from("<I", data, pos + 32)
        name = data[pos + 40: pos + 40 + plen].decode("utf-8")
        entries[name] = (foff, fsize)
        pos += rec_size
    return data, entries, pos  # pos == start of the data section


def main():
    dkb = Path(sys.argv[1]) if len(sys.argv) > 1 else DKB
    data, entries, data_start = read_dkb_table(dkb)
    out = [
        "// Generated by export_mrsim_lib.py — do not edit by hand.",
        "// MRSIM track-object definitions (gates, poles, cubes, flags...)",
        f"// extracted from {dkb.name}. Keys are the game's include paths.",
        "export const MRSIM_LIB = {",
    ]
    for rel in LIB_FILES:
        full = BASE + rel
        if full not in entries:
            print(f"!! missing from archive: {full}", file=sys.stderr)
            continue
        off, size = entries[full]
        xml = data[data_start + off: data_start + off + size].decode("utf-8")
        xml = xml.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
        out.append(f"  {full!r}: `{xml}`,")
        print(f"{size:>7}  {full}")
    out.append("};\n")
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(LIB_FILES)} files)")


if __name__ == "__main__":
    main()
