// Generated by export_mrsim_lib.py — do not edit by hand.
// MRSIM track-object definitions (gates, poles, cubes, flags...)
// extracted from MRSIM.dkb. Keys are the game's include paths.
export const MRSIM_LIB = {
  '/Data/Simulations/Multirotor/5x5Gate.xml': `<Simulation>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Entity name="5x5Gate">
        <Entity>
            <RenderInstance group="5x5Gate Instance Group"/>
            <WorldFromEntityComponent/>
            <SimC>
                void Init(uint initEntity)
                {
                    // Choose artwork randomly from the atlas.
                    const vec4 entries[] = vec4[](
                        vec4(.25, .5, .25, .5),
                        vec4(.5, .5, .25, .5),
                        vec4(.75, .5, .25, .5),
                        vec4(0, 0, .25, .5),
                        vec4(.25, 0, .25, .5),
                        vec4(.5, 0, .25, .5)
                    );
                    EntitySetRenderInstanceData(initEntity, 0u, entries[initEntity % 4u]);
                }
            </SimC>
        </Entity>
        <Entity name="Passage Geometry">
            <WorldFromEntityComponent/>
            <Polyhedron binaryModelFile="5x5Gate.model" part="PassageGeometry"/>
            <StaticContact material="-1"/>

            <Entity name="CheckpointReference">
                <WorldFromEntityComponent x="1.05" z=".75"/>
            </Entity>
            <Checkpoint/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x=".15" z=".75"/>
            <Box x=".3" y=".01" z="1.5"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="2" z=".75"/>
            <Box x=".3" y=".01" z="1.5"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.05" z="1.65"/>
            <Box x="2.1" y=".01" z=".3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="0" z=".9"/>
            <Cylinder radius=".02" height="1.8"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="2.1" z=".9"/>
            <Cylinder radius=".02" height="1.8"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.05" z="1.8" ry="1" angle="1.570796"/>
            <Cylinder radius=".02" height="2.1"/>
            <StaticContact material="TrackPart"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/5x5StartFinishGate.xml': `<Simulation>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Include file="DroneTrackMaterials.xml"/>

    <Entity name="5x5Gate">
        <Entity name="Passage Geometry">
            <WorldFromEntityComponent/>
            <Polyhedron binaryModelFile="5x5Gate.model" part="PassageGeometry"/>
            <StaticContact material="-1"/>

            <Entity name="CheckpointReference">
                <WorldFromEntityComponent x="1.05" z=".75"/>
            </Entity>
            <Checkpoint/>
        </Entity>
        <Entity>
            <RenderInstance group="5x5Gate Instance Group"/>
            <WorldFromEntityComponent/>
            <SimC>
                void Init(uint initEntity)
                {
                    EntitySetRenderInstanceData(initEntity, 0u, vec4(0, .5, .25, .5));
                }
            </SimC>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x=".15" z=".75"/>
            <Box x=".3" y=".01" z="1.5"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="2" z=".75"/>
            <Box x=".3" y=".01" z="1.5"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.05" z="1.65"/>
            <Box x="2.1" y=".01" z=".3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="0" z=".9"/>
            <Cylinder radius=".02" height="1.8"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="2.1" z=".9"/>
            <Cylinder radius=".02" height="1.8"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.05" z="1.8" ry="1" angle="1.570796"/>
            <Cylinder radius=".02" height="2.1"/>
            <StaticContact material="TrackPart"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/7x6Gate.xml': `<Simulation>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Entity name="7x6Gate">
        <Entity name="Passage Geometry">
            <WorldFromEntityComponent/>
            <Polyhedron binaryModelFile="7x6Gate.model" part="PassageGeometry"/>
            <StaticContact material="-1"/>
            <Entity name="CheckpointReference">
                <WorldFromEntityComponent x="1.5" z=".9"/>
            </Entity>
            <Checkpoint/>
        </Entity>
        <Entity>
            <RenderInstance group="7x6Gate Instance Group"/>
            <WorldFromEntityComponent/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x=".2" z=".9"/>
            <Box x=".4" y=".01" z="1.8"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="2.8" z=".9"/>
            <Box x=".4" y=".01" z="1.8"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.5" z="2.05"/>
            <Box x="3" y=".01" z=".5"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="0" z="1.15"/>
            <Cylinder radius=".02" height="2.3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="3" z="1.15"/>
            <Cylinder radius=".02" height="2.3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.5" z="2.3" ry="1" angle="1.570796"/>
            <Cylinder radius=".02" height="3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/7x6StartFinishGate.xml': `<Simulation>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Include file="DroneTrackMaterials.xml"/>

    <Entity name="7x6Gate">
        <Entity name="Timing Gate">
            <WorldFromEntityComponent/>
            <Polyhedron binaryModelFile="7x6Gate.model" part="PassageGeometry"/>
            <StaticContact material="-1"/>
            <Entity name="CheckpointReference">
                <WorldFromEntityComponent x="1.5" z=".9"/>
            </Entity>
            <Checkpoint/>
        </Entity>
        <Entity>
            <BinaryModelRenderer file="7x6Gate.model" assignDefaultMaterials="false">
                <Part name="PVC" material="PVCMaterial"/>
                <Part name="TopPanel" material="StartFinishGateTopMaterial"/>
                <Part name="TopPanelBack" material="GateSideMaterial"/>
                <Part name="LeftPanel" material="GateSideMaterial"/>
                <Part name="RightPanel" material="GateSideMaterial"/>
            </BinaryModelRenderer>
            <WorldFromEntityComponent/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x=".2" z=".9"/>
            <Box x=".4" y=".01" z="1.8"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="2.8" z=".9"/>
            <Box x=".4" y=".01" z="1.8"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.5" z="2.05"/>
            <Box x="3" y=".01" z=".5"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="0" z="1.15"/>
            <Cylinder radius=".02" height="2.3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="3" z="1.15"/>
            <Cylinder radius=".02" height="2.3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.5" z="2.3" ry="1" angle="1.570796"/>
            <Cylinder radius=".02" height="3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/5x5Tower.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>

    <Entity>
        <WorldFromEntityComponent x="0" z=".9"/>
        <Cylinder radius=".02" height="1.8"/>
        <StaticContact material="TrackPart"/>
        <MeshRendererComponent material="PVCMaterial"/>
    </Entity>

    <Entity>
        <WorldFromEntityComponent x="2.1" z=".9"/>
        <Cylinder radius=".02" height="1.8"/>
        <StaticContact material="TrackPart"/>
        <MeshRendererComponent material="PVCMaterial"/>
    </Entity>

    <Entity>
        <WorldFromEntityComponent x="1.05" z="1.64"/>
        <Box x="2.1" y=".01" z=".3"/>
        <StaticContact material="TrackPart"/>
        <MeshRendererComponent material="GateTopMaterial"/>
    </Entity>

    <Transform z="1.8">
        <Include file="5x5Gate.xml"/>
    </Transform>

</Simulation>
`,
  '/Data/Simulations/Multirotor/7x6Tower.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>

    <Entity>
        <WorldFromEntityComponent x="0" z="1.15"/>
        <Cylinder radius=".02" height="2.3"/>
        <StaticContact material="TrackPart"/>
        <MeshRendererComponent material="PVCMaterial"/>
    </Entity>

    <Entity>
        <WorldFromEntityComponent x="3" z="1.15"/>
        <Cylinder radius=".02" height="2.3"/>
        <StaticContact material="TrackPart"/>
        <MeshRendererComponent material="PVCMaterial"/>
    </Entity>

    <Entity>
        <WorldFromEntityComponent x="1.5" z="2.05"/>
        <Box x="3" y=".01" z=".5"/>
        <StaticContact material="TrackPart"/>
        <MeshRendererComponent material="GateTopMaterial"/>
    </Entity>

    <Transform z="2.3">
        <Include file="7x6Gate.xml"/>
    </Transform>

</Simulation>
`,
  '/Data/Simulations/Multirotor/4x7Hurdle.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Entity name="4x7Hurdle">
        <Entity>
            <WorldFromEntityComponent x="1.05" z=".6"/>
            <Box x="2.1" y=".01" z="1.2"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="GateSideMaterial"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/5x10Hurdle.xml': `<Simulation>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Material name="HurdleMaterial">
        <PBR>
            <baseColor x=".6" y=".6" z=".6"/>
            <roughness value=".4"/>
            <metallic value="0"/>
        </PBR>
    </Material>

    <Entity name="5x10Hurdle">
        <WorldFromEntityComponent x="1.5" z=".75"/>
        <Box x="3" y=".01" z="1.5"/>
        <StaticContact material="TrackPart"/>
        <MeshRendererComponent material="GateSideMaterial"/>
        <Entity name="Passage Geometry">
            <WorldFromEntityComponent x="1.5" z="6.5"/>
            <Box x="6" y=".01" z="10"/>
            <StaticContact material="-1"/>
            <Entity name="CheckpointReference">
                <WorldFromEntityComponent x="1.5" z="2.5"/>
            </Entity>
            <Checkpoint/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/7x16Hurdle.xml': `<Simulation>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Material name="HurdleMaterial">
        <PBR>
            <baseColor x=".6" y=".6" z=".6"/>
            <roughness value=".4"/>
            <metallic value="0"/>
        </PBR>
    </Material>

    <Entity name="7x16Hurdle">
        <WorldFromEntityComponent x="2.5" z="1.05"/>
        <Box x="5" y=".01" z="2.1"/>
        <StaticContact material="TrackPart"/>
        <MeshRendererComponent material="GateSideMaterial"/>
        <Entity name="Passage Geometry">
            <WorldFromEntityComponent x="1.5" z="6.5"/>
            <Box x="6" y=".01" z="10"/>
            <StaticContact material="-1"/>
            <Entity name="CheckpointReference">
                <WorldFromEntityComponent x="1.5" z="2.5"/>
            </Entity>
            <Checkpoint/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/DiveGate.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Entity name="DiveGate">
        <Entity>
            <Transform y="-1.35" z="4.5">
                <StaticContact material="TrackPart">
                    <Geometry>
                        <Box x="3" y=".3" z=".01"/>
                    </Geometry>
                    <StandardRendering material="GateTopMaterial"/>
                </StaticContact>
            </Transform>
        </Entity>
        <Entity>
            <Transform y="1.35" z="4.5">
                <StaticContact material="TrackPart">
                    <Geometry>
                        <Box x="3" y=".3" z=".01"/>
                    </Geometry>
                    <StandardRendering material="GateTopMaterial"/>
                </StaticContact>
            </Transform>
        </Entity>
        <Entity>
            <Transform x="-1.35" z="4.5">
                <StaticContact material="TrackPart">
                    <Geometry>
                        <Box x=".3" y="2.4" z=".01"/>
                    </Geometry>
                    <StandardRendering material="GateTopMaterial"/>
                </StaticContact>
            </Transform>
        </Entity>
        <Entity>
            <Transform x="1.35" z="4.5">
                <StaticContact material="TrackPart">
                    <Geometry>
                        <Box x=".3" y="2.4" z=".01"/>
                    </Geometry>
                    <StandardRendering material="GateTopMaterial"/>
                </StaticContact>
            </Transform>
        </Entity>

        <Entity>
            <Transform x="-1.5" y="-1.5" z="2.25">
                <StaticContact material="TrackPart">
                    <Geometry>
                        <Cylinder radius=".02" height="4.5"/>
                    </Geometry>
                    <StandardRendering material="PVCMaterial"/>
                </StaticContact>
            </Transform>
        </Entity>
        <Entity>
            <Transform x="1.5" y="-1.5" z="2.25">
                <StaticContact material="TrackPart">
                    <Geometry>
                        <Cylinder radius=".02" height="4.5"/>
                    </Geometry>
                    <StandardRendering material="PVCMaterial"/>
                </StaticContact>
            </Transform>
        </Entity>
        <Entity>
            <Transform x="1.5" y="1.5" z="2.25">
                <StaticContact material="TrackPart">
                    <Geometry>
                        <Cylinder radius=".02" height="4.5"/>
                    </Geometry>
                    <StandardRendering material="PVCMaterial"/>
                </StaticContact>
            </Transform>
        </Entity>
        <Entity>
            <Transform x="-1.5" y="1.5" z="2.25">
                <StaticContact material="TrackPart">
                    <Geometry>
                        <Cylinder radius=".02" height="4.5"/>
                    </Geometry>
                    <StandardRendering material="PVCMaterial"/>
                </StaticContact>
            </Transform>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/7x7DiveGate.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Entity name="7x7DiveGate">
        <Transform z="2.7">
            <Entity name="Passage Geometry">
                <WorldFromEntityComponent/>
                <Polyhedron binaryModelFile="7x7DiveGate.model" part="PassageGeometry"/>
                <StaticContact material="-1"/>
                <Entity name="CheckpointReference">
                    <WorldFromEntityComponent rx="1" angle="-1.570796"/>
                </Entity>
                <Checkpoint/>
            </Entity>
            <Entity>
                <RenderInstance group="7x7DiveGate Instance Group"/>
                <WorldFromEntityComponent/>
            </Entity>
        </Transform>

        <Entity>
            <WorldFromEntityComponent x="1.275" z="2.7"/>
            <Box x=".45" y="3" z=".01"/>
            <StaticContact material="TrackPart"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent x="-1.275" z="2.7"/>
            <Box x=".45" y="3" z=".01"/>
            <StaticContact material="TrackPart"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent y="1.275" z="2.7"/>
            <Box x="2.1" y=".45" z=".01"/>
            <StaticContact material="TrackPart"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent y="-1.275" z="2.7"/>
            <Box x="2.1" y=".45" z=".01"/>
            <StaticContact material="TrackPart"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent x="-1.5" y="-1.5" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <MeshRendererComponent material="PVCMaterial"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.5" y="-1.5" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <MeshRendererComponent material="PVCMaterial"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.5" y="1.5" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <MeshRendererComponent material="PVCMaterial"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="-1.5" y="1.5" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <MeshRendererComponent material="PVCMaterial"/>
            <StaticContact material="TrackPart"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/7x7ClimbGate.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Entity name="7x7ClimbGate">
        <Transform z="2.7">
            <Entity name="Passage Geometry">
                <WorldFromEntityComponent/>
                <Polyhedron binaryModelFile="7x7ClimbGate.model" part="PassageGeometry"/>
                <StaticContact material="-1"/>
                <Entity name="CheckpointReference">
                    <WorldFromEntityComponent rx="1" angle="1.570796"/>
                </Entity>
                <Checkpoint/>
            </Entity>
            <Entity>
                <RenderInstance group="7x7ClimbGate Instance Group"/>
                <WorldFromEntityComponent/>
            </Entity>
        </Transform>

        <Entity>
            <WorldFromEntityComponent x="1.2" z="2.7"/>
            <Box x=".3" y="2.7" z=".01"/>
            <StaticContact material="TrackPart"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent x="-1.2" z="2.7"/>
            <Box x=".3" y="2.7" z=".01"/>
            <StaticContact material="TrackPart"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent y="1.2" z="2.7"/>
            <Box x="2.1" y=".3" z=".01"/>
            <StaticContact material="TrackPart"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent y="-1.2" z="2.7"/>
            <Box x="2.1" y=".3" z=".01"/>
            <StaticContact material="TrackPart"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent x="-1.35" y="-1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.35" y="-1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.35" y="1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="-1.35" y="1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/7x7DiveBox.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Entity name="7x7DiveBox">
        <Transform z="2.7">
            <Entity name="Passage Geometry">
                <WorldFromEntityComponent/>
                <Box x="2.7" y="2.7" z=".01"/>
                <StaticContact material="-1"/>
                <Entity name="CheckpointReference">
                    <WorldFromEntityComponent rx="1" angle="-1.570796"/>
                </Entity>
                <Checkpoint/>
            </Entity>
        </Transform>
        Side walls
        <Entity>
            <WorldFromEntityComponent x="-1.35" z="1.35"/>
            <Box x=".01" y="2.7" z="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="GateSideMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.35" z="1.35"/>
            <Box x=".01" y="2.7" z="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="GateSideMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent y="1.35" z="1.35"/>
            <Box x="2.7" y=".01" z="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="GateSideMaterial"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent x="-1.35" y="-1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.35" y="-1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.35" y="1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="-1.35" y="1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>

        Top poles
        <Entity>
            <WorldFromEntityComponent x="-1.35" z="2.7" rx="1" angle="1.570796"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent x="1.35" z="2.7" rx="1" angle="1.570796"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent y="-1.35" z="2.7" ry="1" angle="1.570796"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent y="1.35" z="2.7" ry="1" angle="1.570796"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/7x7DiveBoxCorner.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Entity name="7x7DiveBox">
        <Transform z="2.7">
            <Entity name="Passage Geometry">
                <WorldFromEntityComponent/>
                <Box x="2.7" y="2.7" z=".01"/>
                <StaticContact material="-1"/>
                <Entity name="CheckpointReference">
                    <WorldFromEntityComponent rx="1" angle="-1.570796"/>
                </Entity>
                <Checkpoint/>
            </Entity>
        </Transform>
        Side walls
        <Entity>
            <WorldFromEntityComponent x="-1.35" z="1.35"/>
            <Box x=".01" y="2.7" z="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="GateSideMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent y="1.35" z="1.35"/>
            <Box x="2.7" y=".01" z="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="GateSideMaterial"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent x="-1.35" y="-1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.35" y="-1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.35" y="1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="-1.35" y="1.35" z="1.35"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>

        Top poles
        <Entity>
            <WorldFromEntityComponent x="-1.35" z="2.7" rx="1" angle="1.570796"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent x="1.35" z="2.7" rx="1" angle="1.570796"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent y="-1.35" z="2.7" ry="1" angle="1.570796"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>

        <Entity>
            <WorldFromEntityComponent y="1.35" z="2.7" ry="1" angle="1.570796"/>
            <Cylinder radius=".02" height="2.7"/>
            <StaticContact material="TrackPart"/>
            <MeshRendererComponent material="PVCMaterial"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/CarouselDown.xml': `<Simulation>
    <Transform x="-.6">
        <Include file="Flag.xml"/>
    </Transform>
    <Include file="5x5Gate.xml"/>
</Simulation>
`,
  '/Data/Simulations/Multirotor/7x7Mat.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Entity name="7x7Mat">
        <WorldFromEntityComponent/>

        <BinaryModelRenderer file="7x7Mat.model" assignDefaultMaterials="false" cullBackfaces="true">
            <Material name="PanelMaterial">
            {
                definition: "PBRBaseColorTextured",
                uniforms:
                {
                    roughness: .4, metallic: 0
                },
                samplers:
                {
                    baseColorTexture: {texture: "GatePaint/7x7Mat.png"},
                }
            }
            </Material>
            <Part name="PVC" material="PVCMaterial"/>
            <Part name="Panel" material="PanelMaterial"/>
        </BinaryModelRenderer>

        <Entity>
            <WorldFromEntityComponent x="0" y="0" z=".0125"/>
            <Box x="3" y="3" z=".025"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.5" y="0" z=".02" rx="1" angleDegrees="-90"/>
            <Cylinder radius=".02" height="3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="-1.5" y="0" z=".02" rx="1" angleDegrees="-90"/>
            <Cylinder radius=".02" height="3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="0" y="1.5" z=".02" ry="1" angleDegrees="90"/>
            <Cylinder radius=".02" height="3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="0" y="-1.5" z=".02" ry="1" angleDegrees="90"/>
            <Cylinder radius=".02" height="3"/>
            <StaticContact material="TrackPart"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/StartBlock.xml': `<Simulation>
    <ContactMaterial name="TerrainMaterial"/>

    <Material name="GrayPaint">
        <PBR>
            <baseColor x=".4" y=".4" z=".4"/>
            <roughness value=".6"/>
            <metallic value="0"/>
        </PBR>
    </Material>

    <Entity name="StartBlock">
        <Entity>
            <WorldFromEntityComponent x=".1"/>
            <Box x=".1" y=".2" z=".2"/>
            <StaticContact material="TerrainMaterial"/>
            <MeshRendererComponent material="GrayPaint" subdivisions="1"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="-.1"/>
            <Box x=".1" y=".2" z=".2"/>
            <StaticContact material="TerrainMaterial"/>
            <MeshRendererComponent material="GrayPaint" subdivisions="1"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/Flag.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>

    <Entity name="Flag">
        <Entity>
            <RenderInstance group="Flag Instance Group"/>
            <WorldFromEntityComponent/>
            <SimC>
                void Init(uint initEntity)
                {
                    // Choose artwork randomly from the atlas.
                    const vec4 entries[] = vec4[](
                        vec4(0, 0, .5, 1),
                        vec4(.25, 0, .5, 1),
                        vec4(.5, 0, .5, 1)
                    );
                    EntitySetRenderInstanceData(initEntity, 0u, entries[initEntity % 3u]);
                }
            </SimC>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="0" z="1.9"/>
            <Cylinder radius=".04" height="2.8"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent/>
            <Cylinder radius=".02" height="1"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent/>
            <Polyhedron binaryModelFile="Flag.model" part="Flag"/>
            <StaticContact material="TrackPart"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/Flag180.xml': `<Simulation>
    <Transform rz="1" angle="3.14159">
        <Include file="Flag.xml"/>
    </Transform>
</Simulation>`,
  '/Data/Simulations/Multirotor/FlagPassRight.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>

    <Entity name="FlagPassRight">
        <Transform>
            <Include file="/Data/Simulations/Multirotor/Flag.xml"/>
        </Transform>

        <Transform z="3">
            <Include file="HalfPlanePassageRight.xml"/>
        </Transform>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/FlagPassLeft.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>

    <Entity name="FlagPassLeft">
        <Transform rz="-1" angleDegrees="180">
            <Include file="/Data/Simulations/Multirotor/Flag.xml"/>
        </Transform>

        <Transform z="3">
            <Include file="HalfPlanePassageLeft.xml"/>
        </Transform>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/HalfPlanePassageRight.xml': `<Simulation>
    <Entity name="HalfPlanePassageRight">
        <WorldFromEntityComponent x="10"/>
        <Box x="20" y=".001" z="20"/>
        <StaticContact material="-1"/>
        <Entity name="CheckpointReference">
            <WorldFromEntityComponent x="1"/>
        </Entity>
        <Checkpoint/>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/HalfPlanePassageLeft.xml': `<Simulation>
    <Entity name="HalfPlanePassageLeft">
        <WorldFromEntityComponent x="-10"/>
        <Box x="20" y=".001" z="20"/>
        <StaticContact material="-1"/>
        <Entity name="CheckpointReference">
            <WorldFromEntityComponent x="-1"/>
        </Entity>
        <Checkpoint/>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/DroneTrackInstanceGroups.xml': `<Simulation>
    <Include file="DroneTrackMaterials.xml"/>

    <Entity name="5x5Gate Instance Group">
        <BinaryModelRenderer file="5x5Gate.model" assignDefaultMaterials="false" cullBackfaces="true">
            <Part name="PVC" material="PVCInstancingMaterial"/>
            <Part name="Fabric" material="5x5GateFabricInstancingMaterial"/>
        </BinaryModelRenderer>
        <RenderInstanceGroup extraVec4Count="1"/>
    </Entity>

    <Entity name="7x6Gate Instance Group">
        <BinaryModelRenderer file="7x6Gate.model" assignDefaultMaterials="false" cullBackfaces="true">
            <Part name="PVC" material="PVCInstancingMaterial"/>
            <Part name="TopPanel" material="GateTopInstancingMaterial"/>
            <Part name="TopPanelBack" material="GateSideInstancingMaterial"/>
            <Part name="LeftPanel" material="GateSideInstancingMaterial"/>
            <Part name="RightPanel" material="GateSideInstancingMaterial"/>
        </BinaryModelRenderer>
        <RenderInstanceGroup/>
    </Entity>

    <Entity name="Flag Instance Group">
        <BinaryModelRenderer file="Flag.model" cullBackfaces="true">
            <Part name="Stalk" material="FlagStalkInstancingMaterial"/>
            <Part name="Sleeve" material="FlagPoleInstancingMaterial"/>
            <Part name="Flag" material="FlagFabricInstancingMaterial"/>
        </BinaryModelRenderer>
        <RenderInstanceGroup extraVec4Count="1"/>
    </Entity>

    <Entity name="7x7DiveGate Instance Group">
        <BinaryModelRenderer file="7x7DiveGate.model" assignDefaultMaterials="false" cullBackfaces="true">
            <Part name="PVC" material="PVCInstancingMaterial"/>
            <Part name="SquarePanel" material="GateSideInstancingMaterial"/>
            <Part name="FrontPanel" material="GateTopInstancingMaterial"/>
            <Part name="BackPanel" material="GateTopInstancingMaterial"/>
        </BinaryModelRenderer>
        <RenderInstanceGroup/>
    </Entity>

    <Entity name="7x7ClimbGate Instance Group">
        <BinaryModelRenderer file="7x7ClimbGate.model" assignDefaultMaterials="false" cullBackfaces="true">
            <Part name="PVC" material="PVCInstancingMaterial"/>
            <Part name="SquarePanel" material="GateSideInstancingMaterial"/>
            <Part name="FrontPanel" material="GateTopInstancingMaterial"/>
            <Part name="BackPanel" material="GateTopInstancingMaterial"/>
        </BinaryModelRenderer>
        <RenderInstanceGroup/>
    </Entity>

    <Entity name="Champs25Gate Instance Group">
        <BinaryModelRenderer file="/Data/Simulations/Multirotor/Gates/Champs25Gate.model" assignDefaultMaterials="false" cullBackfaces="true">
            <Part name="LEDGate" material="GateLEDMaterial"/>
            <Part name="Gate" material="GateSideInstancingMaterial"/>
        </BinaryModelRenderer>
        <RenderInstanceGroup extraVec4Count="2"/>
    </Entity>

    <Entity name="Champs25Pole Instance Group">
        <BinaryModelRenderer file="/Data/Simulations/Multirotor/Gates/Champs25Pole.model" assignDefaultMaterials="false" cullBackfaces="true">
            <Part name="Sleeve" material="GateLEDMaterial"/>
            <Part name="Stalk" material="FlagStalkInstancingMaterial"/>
        </BinaryModelRenderer>
        <RenderInstanceGroup extraVec4Count="2"/>
    </Entity>

    <Entity name="Pole Gate Inner Instance Group">
        <WorldFromEntityComponent/>
        <Cylinder radius=".02" height="2"/>
        <MeshRendererComponent material="FlagPoleInstancingMaterial" subdivisions="8"/>
        <RenderInstanceGroup/>
    </Entity>

    <Entity name="Pole Gate Padding Instance Group">
        <WorldFromEntityComponent/>
        <Cylinder radius=".04" height="1.9"/>
        <MeshRendererComponent material="PoleGateWhiteInstancingMaterial" subdivisions="8"/>
        <RenderInstanceGroup/>
    </Entity>

    <Entity name="Pole Gate Tape Instance Group">
        <WorldFromEntityComponent/>
        <Cylinder radius=".043" height=".04"/>
        <MeshRendererComponent material="PoleGateTapeInstancingMaterial" subdivisions="8"/>
        <RenderInstanceGroup extraVec4Count="1"/>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/RaceLEDs.xml': `<Simulation>
    <Include file="/Data/Simulations/Multirotor/DroneRenderingMaterials.xml"/>

    <Entity name="RaceLEDs">
        <WorldFromEntityComponent/>
        <ParentFromEntityComponent/>
        <BinaryModelRenderer file="RaceLEDs.model" assignDefaultMaterials="true"/>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/Gates/PoleGates.xml': `<Simulation>
    <Macro name="PaddedPoleNoTape">
        <Entity>
            <WorldFromEntityComponent/>
            <RenderInstance group="Pole Gate Inner Instance Group"/>
            <Cylinder radius=".02" height="2"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent/>
            <RenderInstance group="Pole Gate Padding Instance Group"/>
            <Cylinder radius=".04" height="1.9"/>
            <StaticContact material="TrackPart"/>
        </Entity>
    </Macro>
    <Macro name="PoleGateBlueTape">
        <RenderInstance group="Pole Gate Tape Instance Group"/>
        <SimC>
            uint thisEntity;
            EntitySetRenderInstanceData(thisEntity, 0u, vec4(0, 0, .5, 1));
        </SimC>
    </Macro>
    <Macro name="PoleGateRedTape">
        <RenderInstance group="Pole Gate Tape Instance Group"/>
        <SimC>
            uint thisEntity;
            EntitySetRenderInstanceData(thisEntity, 0u, vec4(.5, 0, 0, 1));
        </SimC>
    </Macro>
    <Macro name="PaddedPole">
        <Instance macro="PaddedPoleNoTape"/>
        <Entity>
            <WorldFromEntityComponent/>
            <Instance macro="PoleGateBlueTape"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent z=".4"/>
            <Instance macro="PoleGateRedTape"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent z="-.4"/>
            <Instance macro="PoleGateRedTape"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent z=".8"/>
            <Instance macro="PoleGateBlueTape"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent z="-.8"/>
            <Instance macro="PoleGateBlueTape"/>
        </Entity>
    </Macro>

    <Macro name="PoleSquarePassage">
        <Entity>
            <WorldFromEntityComponent/>
            <Box x="2" y=".001" z="2"/>
            <StaticContact material="-1"/>
            <Entity name="CheckpointReference">
                <WorldFromEntityComponent/>
            </Entity>
            <Checkpoint/>
        </Entity>
    </Macro>

    <Macro name="PaddedPoleSquare">
        <Transform y="1" z="0" ry="1" angleDegrees="90">
            <Instance macro="PaddedPole"/>
        </Transform>
        <Transform y="-1" z="0" ry="1" angleDegrees="90">
            <Instance macro="PaddedPole"/>
        </Transform>
        <Transform x="1" z="0" rx="1" angleDegrees="90">
            <Instance macro="PaddedPole"/>
        </Transform>
        <Transform x="-1" z="0" rx="1" angleDegrees="90">
            <Instance macro="PaddedPole"/>
        </Transform>
    </Macro>

    <Macro name="PaddedPoleCubeTop">
        <Transform z="2">
            <Instance macro="PaddedPoleSquare"/>
        </Transform>

        <Transform x="1" y="1" z="1">
            <Instance macro="PaddedPole"/>
        </Transform>
        <Transform x="-1" y="1" z="1">
            <Instance macro="PaddedPole"/>
        </Transform>
        <Transform x="1" y="-1" z="1">
            <Instance macro="PaddedPole"/>
        </Transform>
        <Transform x="-1" y="-1" z="1">
            <Instance macro="PaddedPole"/>
        </Transform>

        <Transform z="2" rx="1" angleDegrees="-90">
            <Entity name="topEntry">
                <Instance macro="PoleSquarePassage"/>
            </Entity>
        </Transform>
        <Transform z="2" rx="1" angleDegrees="90">
            <Entity name="topExit">
                <Instance macro="PoleSquarePassage"/>
            </Entity>
        </Transform>
        <Transform v="0, -1, 1" rz="-1" angleDegrees="180">
            <Entity name="frontExit">
                <Instance macro="PoleSquarePassage"/>
            </Entity>
        </Transform>
        <Transform v="0, -1, 1">
            <Entity name="frontEntry">
                <Instance macro="PoleSquarePassage"/>
            </Entity>
        </Transform>
        <Transform v="0, 1, 1">
            <Entity name="backExit">
                <Instance macro="PoleSquarePassage"/>
            </Entity>
        </Transform>
        <Transform v="0, 1, 1" rz="-1" angleDegrees="180">
            <Entity name="backEntry">
                <Instance macro="PoleSquarePassage"/>
            </Entity>
        </Transform>
        <Transform v="-1, 0, 1" rz="1" angleDegrees="-90">
            <Entity name="leftEntry">
                <Instance macro="PoleSquarePassage"/>
            </Entity>
        </Transform>
        <Transform v="-1, 0, 1" rz="1" angleDegrees="90">
            <Entity name="leftExit">
                <Instance macro="PoleSquarePassage"/>
            </Entity>
        </Transform>
        <Transform v="1, 0, 1" rz="1" angleDegrees="90">
            <Entity name="rightEntry">
                <Instance macro="PoleSquarePassage"/>
            </Entity>
        </Transform>
        <Transform v="1, 0, 1" rz="1" angleDegrees="-90">
            <Entity name="rightExit">
                <Instance macro="PoleSquarePassage"/>
            </Entity>
        </Transform>
    </Macro>

    <Macro name="PipeCube">
        <Transform z=".04">
            <Instance macro="PaddedPoleSquare"/>

            <Instance macro="PaddedPoleCubeTop"/>
        </Transform>
    </Macro>

    <Macro name="PipeDoubleCube">
        <Transform z=".04">
            <Instance macro="PaddedPoleSquare"/>

            <Entity name="lower">
                <Instance macro="PaddedPoleCubeTop"/>
            </Entity>

            <Transform z="2">
                <Entity name="upper">
                    <Instance macro="PaddedPoleCubeTop"/>
                </Entity>
            </Transform>
        </Transform>
    </Macro>

    <Macro name="PipeLadder">
        <Transform z=".04">
            <Transform y="1" z="0" ry="1" angleDegrees="90">
                <Instance macro="PaddedPoleNoTape"/>
            </Transform>
            <Transform y="-1" z="0" ry="1" angleDegrees="90">
                <Instance macro="PaddedPoleNoTape"/>
            </Transform>
            <Transform x="1" z="0" rx="1" angleDegrees="90">
                <Instance macro="PaddedPoleNoTape"/>
            </Transform>
            <Transform x="-1" z="0" rx="1" angleDegrees="90">
                <Instance macro="PaddedPoleNoTape"/>
            </Transform>

            <Transform ry="1" angleDegrees="90">
                <Instance macro="PaddedPoleNoTape"/>
            </Transform>
            <Transform v="0, 0, 2" ry="1" angleDegrees="90">
                <Instance macro="PaddedPole"/>
            </Transform>
            <Transform v="0, 0, 4" ry="1" angleDegrees="90">
                <Instance macro="PaddedPole"/>
            </Transform>

            <Transform v="1, 1" rx="1" angleDegrees="30">
                <Transform z="1">
                    <Instance macro="PaddedPoleNoTape"/>
                </Transform>
            </Transform>
            <Transform v="-1, 1" rx="1" angleDegrees="30">
                <Transform z="1">
                    <Instance macro="PaddedPoleNoTape"/>
                </Transform>
            </Transform>
            <Transform v="1, -1" rx="1" angleDegrees="-30">
                <Transform z="1">
                    <Instance macro="PaddedPoleNoTape"/>
                </Transform>
            </Transform>
            <Transform v="-1, -1" rx="1" angleDegrees="-30">
                <Transform z="1">
                    <Instance macro="PaddedPoleNoTape"/>
                </Transform>
            </Transform>

            <Transform x="1" z="1">
                <Instance macro="PaddedPole"/>
                <Transform z="2">
                    <Instance macro="PaddedPole"/>
                </Transform>
            </Transform>
            <Transform x="-1" z="1">
                <Instance macro="PaddedPole"/>
                <Transform z="2">
                    <Instance macro="PaddedPole"/>
                </Transform>
            </Transform>

            <Entity name="lower">
                <Transform v="0, 0, 1">
                    <Entity name="front">
                        <Instance macro="PoleSquarePassage"/>
                    </Entity>
                </Transform>
    
                <Transform v="0, 0, 1" rz="1" angleDegrees="180">
                    <Entity name="back">
                        <Instance macro="PoleSquarePassage"/>
                    </Entity>
                </Transform>
            </Entity>

            <Entity name="upper">
                <Transform v="0, 0, 3">
                    <Entity name="front">
                        <Instance macro="PoleSquarePassage"/>
                    </Entity>
                </Transform>

                <Transform v="0, 0, 3" rz="1" angleDegrees="180">
                    <Entity name="back">
                        <Instance macro="PoleSquarePassage"/>
                    </Entity>
                </Transform>
            </Entity>
        </Transform>
    </Macro>

    <Macro name="PoleQuadrupleLadderPassage">
        <Entity>
            <WorldFromEntityComponent/>
            <Box x="2" y=".001" z="1.5"/>
            <StaticContact material="-1"/>
            <Entity name="CheckpointReference">
                <WorldFromEntityComponent/>
            </Entity>
            <Checkpoint/>
        </Entity>
    </Macro>

    <Macro name="PipeQuadrupleLadder">
        <Transform z=".04">
            <Transform y="1" z="0" ry="1" angleDegrees="90">
                <Instance macro="PaddedPoleNoTape"/>
            </Transform>
            <Transform y="-1" z="0" ry="1" angleDegrees="90">
                <Instance macro="PaddedPoleNoTape"/>
            </Transform>
            <Transform x="1" z="0" rx="1" angleDegrees="90">
                <Instance macro="PaddedPoleNoTape"/>
            </Transform>
            <Transform x="-1" z="0" rx="1" angleDegrees="90">
                <Instance macro="PaddedPoleNoTape"/>
            </Transform>

            <Transform ry="1" angleDegrees="90">
                <Instance macro="PaddedPoleNoTape"/>
            </Transform>
            <Transform v="0, 0, 1.5" ry="1" angleDegrees="90">
                <Instance macro="PaddedPole"/>
            </Transform>
            <Transform v="0, 0, 3" ry="1" angleDegrees="90">
                <Instance macro="PaddedPole"/>
            </Transform>
            <Transform v="0, 0, 4.5" ry="1" angleDegrees="90">
                <Instance macro="PaddedPole"/>
            </Transform>
            <Transform v="0, 0, 6" ry="1" angleDegrees="90">
                <Instance macro="PaddedPole"/>
            </Transform>

            <Entity name="level1">
                <Transform v="0, 0, .75">
                    <Entity name="front">
                        <Instance macro="PoleQuadrupleLadderPassage"/>
                    </Entity>
    
                    <Transform rz="1" angleDegrees="180">
                        <Entity name="back">
                            <Instance macro="PoleQuadrupleLadderPassage"/>
                        </Entity>
                    </Transform>
                </Transform>
            </Entity>

            <Entity name="level2">
                <Transform v="0, 0, 2.25">
                    <Entity name="front">
                        <Instance macro="PoleQuadrupleLadderPassage"/>
                    </Entity>
    
                    <Transform rz="1" angleDegrees="180">
                        <Entity name="back">
                            <Instance macro="PoleQuadrupleLadderPassage"/>
                        </Entity>
                    </Transform>
                </Transform>
            </Entity>

            <Entity name="level3">
                <Transform v="0, 0, 3.75">
                    <Entity name="front">
                        <Instance macro="PoleQuadrupleLadderPassage"/>
                    </Entity>
    
                    <Transform rz="1" angleDegrees="180">
                        <Entity name="back">
                            <Instance macro="PoleQuadrupleLadderPassage"/>
                        </Entity>
                    </Transform>
                </Transform>
            </Entity>

            <Entity name="level4">
                <Transform v="0, 0, 5.25">
                    <Entity name="front">
                        <Instance macro="PoleQuadrupleLadderPassage"/>
                    </Entity>
    
                    <Transform rz="1" angleDegrees="180">
                        <Entity name="back">
                            <Instance macro="PoleQuadrupleLadderPassage"/>
                        </Entity>
                    </Transform>
                </Transform>
            </Entity>

            <Transform v="1, 1" rx="1" angleDegrees="30">
                <Transform z="1">
                    <Instance macro="PaddedPoleNoTape"/>
                </Transform>
            </Transform>
            <Transform v="-1, 1" rx="1" angleDegrees="30">
                <Transform z="1">
                    <Instance macro="PaddedPoleNoTape"/>
                </Transform>
            </Transform>
            <Transform v="1, -1" rx="1" angleDegrees="-30">
                <Transform z="1">
                    <Instance macro="PaddedPoleNoTape"/>
                </Transform>
            </Transform>
            <Transform v="-1, -1" rx="1" angleDegrees="-30">
                <Transform z="1">
                    <Instance macro="PaddedPoleNoTape"/>
                </Transform>
            </Transform>

            <Transform x="1" z="1">
                <Instance macro="PaddedPole"/>
                <Transform z="2">
                    <Instance macro="PaddedPole"/>
                    <Transform z="2">
                        <Instance macro="PaddedPole"/>
                    </Transform>
                </Transform>
            </Transform>
            <Transform x="-1" z="1">
                <Instance macro="PaddedPole"/>
                <Transform z="2">
                    <Instance macro="PaddedPole"/>
                    <Transform z="2">
                        <Instance macro="PaddedPole"/>
                    </Transform>
                </Transform>
            </Transform>
        </Transform>
    </Macro>
</Simulation>`,
  '/Data/Simulations/Multirotor/Gates/Champs25Gate.xml': `<Simulation>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Macro name="Champs25GateLightsOff">
        <Entity name="Champs25Gate">
            <Entity name="graphics">
                <RenderInstance group="Champs25Gate Instance Group"/>
                <WorldFromEntityComponent/>
                <SimC>
                    uint graphicsEntity = FindEntityByName("graphics");
                    EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(0, 0, 0, 1));
                    EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(0, 0, 0, 1));
                </SimC>
            </Entity>
            <Entity name="Passage Geometry">
                <WorldFromEntityComponent/>
                <Polyhedron binaryModelFile="/Data/Simulations/Multirotor/Gates/Champs25Gate.model" part="PassageGeometry"/>
                <StaticContact material="-1"/>
    
                <Entity name="CheckpointReference">
                    <WorldFromEntityComponent x="0" z="1.27"/>
                </Entity>
                <Checkpoint/>
            </Entity>
            <Entity>
                <WorldFromEntityComponent z=".025"/>
                <Box x="2.54" y=".5" z=".05"/>
                <StaticContact material="TrackPart"/>
            </Entity>
            <Entity>
                <WorldFromEntityComponent z="2.515"/>
                <Box x="2.54" y=".5" z=".05"/>
                <StaticContact material="TrackPart"/>
            </Entity>
            <Entity>
                <WorldFromEntityComponent x="1.2456" z="1.27"/>
                <Box x=".05" y=".5" z="2.54"/>
                <StaticContact material="TrackPart"/>
            </Entity>
            <Entity>
                <WorldFromEntityComponent x="-1.2456" z="1.27"/>
                <Box x=".05" y=".5" z="2.54"/>
                <StaticContact material="TrackPart"/>
            </Entity>
        </Entity>
    </Macro>

    <Macro name="Champs25GateRed">
        <Instance macro="Champs25GateLightsOff"/>
        <MakeEntityCurrent name="Champs25Gate.graphics">
            <SimC>
                uint graphicsEntity = FindEntityByName("graphics");
                EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(.3, 0, 0, 1));
                EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(3, 0, 0, 1));
            </SimC>
        </MakeEntityCurrent>
    </Macro>

    <Macro name="Champs25GateGreen">
        <Instance macro="Champs25GateLightsOff"/>
        <MakeEntityCurrent name="Champs25Gate.graphics">
            <SimC>
                uint graphicsEntity = FindEntityByName("graphics");
                EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(0, .3, 0, 1));
                EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(0, 3, 0, 1));
            </SimC>
        </MakeEntityCurrent>
    </Macro>

    <Macro name="Champs25GateBlue">
        <Instance macro="Champs25GateLightsOff"/>
        <MakeEntityCurrent name="Champs25Gate.graphics">
            <SimC>
                uint graphicsEntity = FindEntityByName("graphics");
                EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(0, 0, .3, 1));
                EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(0, 0, 3, 1));
            </SimC>
        </MakeEntityCurrent>
    </Macro>

    <Macro name="Champs25GateYellow">
        <Instance macro="Champs25GateLightsOff"/>
        <MakeEntityCurrent name="Champs25Gate.graphics">
            <SimC>
                uint graphicsEntity = FindEntityByName("graphics");
                EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(.3, .3, 0, 1));
                EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(3, 3, 0, 1));
            </SimC>
        </MakeEntityCurrent>
    </Macro>

    <Macro name="Champs25GateWhite">
        <Instance macro="Champs25GateLightsOff"/>
        <MakeEntityCurrent name="Champs25Gate.graphics">
            <SimC>
                uint graphicsEntity = FindEntityByName("graphics");
                EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(.3, .3, .3, 1));
                EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(3, 3, 3, 1));
            </SimC>
        </MakeEntityCurrent>
    </Macro>
</Simulation>
`,
  '/Data/Simulations/Multirotor/Gates/Champs25Pole.xml': `<Simulation>
    <Include file="/Data/Simulations/Multirotor/DroneTrackMaterials.xml"/>

    <Macro name="Champs25PoleLightsOff">
        <Entity name="Champs25Pole">
            <Entity name="graphics">
                <RenderInstance group="Champs25Pole Instance Group"/>
                <WorldFromEntityComponent/>
                <SimC>
                    uint graphicsEntity = FindEntityByName("graphics");
                    EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(0, 0, 0, 1));
                    EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(0, 0, 0, 1));
                </SimC>
            </Entity>
            <Entity>
                <WorldFromEntityComponent x="0" z="2"/>
                <Cylinder radius=".04" height="3"/>
                <StaticContact material="TrackPart"/>
            </Entity>
            <Entity>
                <WorldFromEntityComponent/>
                <Cylinder radius=".02" height="1"/>
                <StaticContact material="TrackPart"/>
            </Entity>
        </Entity>
    </Macro>
    <Macro name="Champs25PoleRed">
        <Instance macro="Champs25PoleLightsOff"/>
        <MakeEntityCurrent name="Champs25Pole.graphics">
            <SimC>
                uint graphicsEntity = FindEntityByName("graphics");
                EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(.3, 0, 0, 1));
                EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(3, 0, 0, 1));
            </SimC>
        </MakeEntityCurrent>
    </Macro>
    <Macro name="Champs25PoleGreen">
        <Instance macro="Champs25PoleLightsOff"/>
        <MakeEntityCurrent name="Champs25Pole.graphics">
            <SimC>
                uint graphicsEntity = FindEntityByName("graphics");
                EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(0, .3, 0, 1));
                EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(0, 3, 0, 1));
            </SimC>
        </MakeEntityCurrent>
    </Macro>
    <Macro name="Champs25PoleBlue">
        <Instance macro="Champs25PoleLightsOff"/>
        <MakeEntityCurrent name="Champs25Pole.graphics">
            <SimC>
                uint graphicsEntity = FindEntityByName("graphics");
                EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(0, 0, .3, 1));
                EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(0, 0, 3, 1));
            </SimC>
        </MakeEntityCurrent>
    </Macro>
    <Macro name="Champs25PoleYellow">
        <Instance macro="Champs25PoleLightsOff"/>
        <MakeEntityCurrent name="Champs25Pole.graphics">
            <SimC>
                uint graphicsEntity = FindEntityByName("graphics");
                EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(.3, .3, 0, 1));
                EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(3, 3, 0, 1));
            </SimC>
        </MakeEntityCurrent>
    </Macro>
    <Macro name="Champs25PoleWhite">
        <Instance macro="Champs25PoleLightsOff"/>
        <MakeEntityCurrent name="Champs25Pole.graphics">
            <SimC>
                uint graphicsEntity = FindEntityByName("graphics");
                EntitySetRenderInstanceData(graphicsEntity, 0u, vec4(.3, .3, 3, 1));
                EntitySetRenderInstanceData(graphicsEntity, 4u, vec4(3, 3, 3, 1));
            </SimC>
        </MakeEntityCurrent>
    </Macro>
</Simulation>
`,
  '/Data/Simulations/Multirotor/LaunchStands/MetalLaunchStand.xml': `<Simulation>
    <Material name="Paint_-_Enamel_Glossy_(Red)">
    {
        definition: "PBR",
        uniforms:
        {
            baseColor: [.3, .005, .005],
            roughness: .1,
            metallic: 0,
        }
    }
    </Material>

    <Material name="Nylon_12_(with_Formlabs_Fuse_1_3D_Printer)">
    {
        definition: "PBR",
        uniforms:
        {
            baseColor: [.01, .01, .01],
            roughness: .7,
            metallic: 0,
        }
    }
    </Material>

    <Entity name="MetalLaunchStand">
        <WorldFromEntityComponent y="-.125"/>
        <BinaryModelRenderer file="MetalLaunchStand.model" assignDefaultMaterials="true"/>
        <Entity>
            <WorldFromEntityComponent x=".073" z=".0375"/>
            <Box x=".04" y=".25" z=".075"/>
            <StaticContact material="TerrainMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="-.073" z=".0375"/>
            <Box x=".04" y=".25" z=".075"/>
            <StaticContact material="TerrainMaterial"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="0" y="-.095" z=".07"/>
            <Box x=".106" y=".06" z=".007"/>
            <StaticContact material="TerrainMaterial"/>
        </Entity>
        <Entity name="StartPosition">
            <WorldFromEntityComponent y=".03" z=".075"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/LaunchStands/ChampionshipLaunchStand.xml': `<Simulation>
    <Material name="Foam">
    {
        definition: "PBR",
        uniforms:
        {
            baseColor: [.01, .01, .01],
            roughness: .7,
            metallic: 0,
        }
    }
    </Material>

    <Material name="StandPaint">
    {
        definition: "PBR",
        uniforms:
        {
            baseColor: [.3, .005, .005],
            roughness: .1,
            metallic: 0,
        }
    }
    </Material>

    <Entity name="ChampionshipLaunchStand">
        <WorldFromEntityComponent/>
        <BinaryModelRenderer file="ChampionshipLaunchStand.model" assignDefaultMaterials="true"/>
        <ConvexPolySetStaticContact> {binaryModelFile: "ChampionshipLaunchStandCollision.model"} </ConvexPolySetStaticContact>
        <Entity name="StartPosition">
            <WorldFromEntityComponent y=".15" z=".862"/>
        </Entity>
    </Entity>
</Simulation>
`,
  '/Data/Simulations/Multirotor/Furniture/ShadeCanopy.xml': `<Simulation>
    <Include file="/Data/Simulations/Multirotor/DroneContactMaterials.xml"/>

    <Material name="ShadeCanopyFabric">
    {
        definition: "PBR",
        uniforms:
        {
            baseColor: [.05, .05, .5],
            roughness: [.9]
        }
    }
    </Material>

    <Material name="ShadeCanopyFeet">
    {
        definition: "PBR",
        uniforms:
        {
            baseColor: [.05, .05, .05],
            roughness: [.3]
        }
    }
    </Material>

    <Material name="ShadeCanopyLegs">
    {
        definition: "PBR",
        uniforms:
        {
            baseColor: [.5, .5, .5],
            roughness: [.1]
        }
    }
    </Material>

    <Entity name="ShadeCanopy">
        <WorldFromEntityComponent/>
        <BinaryModelRenderer file="ShadeCanopy.model" assignDefaultMaterials="true"/>
        <Entity name="Passage Geometry">
            <WorldFromEntityComponent/>
            <Polyhedron binaryModelFile="ShadeCanopyCollision.model" part="FabricCollision"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.5" y="1.5" z="1"/>
            <Box x=".04" y=".04" z="2"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="-1.5" y="1.5" z="1"/>
            <Box x=".04" y=".04" z="2"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="-1.5" y="-1.5" z="1"/>
            <Box x=".04" y=".04" z="2"/>
            <StaticContact material="TrackPart"/>
        </Entity>
        <Entity>
            <WorldFromEntityComponent x="1.5" y="-1.5" z="1"/>
            <Box x=".04" y=".04" z="2"/>
            <StaticContact material="TrackPart"/>
        </Entity>
    </Entity>
</Simulation>
`,
};
